# Generated by Django 5.2.7 on 2025-11-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professors',
            name='location_gif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professors',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
