# Generated by Django 5.2.7 on 2025-11-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_professors_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='location_gif',
            field=models.ImageField(blank=True, null=True, upload_to='professors/'),
        ),
    ]
