# Generated by Django 5.2.7 on 2025-12-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_alter_professors_location_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='location_images/')),
            ],
        ),
        migrations.AddField(
            model_name='professors',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
