# Generated by Django 5.2.7 on 2025-11-10 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=20)),
                ('visit_purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('대기', '대기'), ('수락', '수락'), ('거절', '거절')], default='대기', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='professors.professors')),
            ],
        ),
    ]
