# Generated by Django 5.2.7 on 2025-11-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
