# Generated by Django 5.2.7 on 2025-11-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_alter_professors_location_gif'),
        ('visit', '0002_visitors_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='professors.professors'),
        ),
    ]
