# Generated by Django 5.2.7 on 2025-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_alter_visitors_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='is_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
