# Generated by Django 5.2.7 on 2025-12-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_visitors_agreed_at_visitors_is_agreed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='agreed_at',
        ),
        migrations.AddField(
            model_name='visitors',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
